# file: config.yaml

# Paths to local models and data
paths:
  mistral_local_path: "/data/gpfs/projects/COMP90055/aticinovic/models/Mistral-7B-v0.3"
  clip_local_path: "/data/gpfs/projects/COMP90055/aticinovic/models/clip-vit-large-patch14"
  image_dir: "/data/gpfs/projects/COMP90055/aticinovic/datasets/coco/train2017"
  annotations_file: "/data/gpfs/projects/COMP90055/aticinovic/datasets/coco/annotations/captions_train2017.json"

  output_dir: "/data/gpfs/projects/COMP90055/aticinovic/outputs"

# Training parameters for Stage 1
training_stage1:
  num_epochs: 15
  batch_size: 18
  learning_rate: 0.0001
  subset_fraction: 0.2
  weight_decay: 0.75
  gradient_accumulation_steps: 2

# Training parameters for Stage 2
training_stage2:
  num_epochs: 20
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.01
  subset_fraction: 0.3
  gradient_accumulation_steps: 4

training_stage2.5:
  num_epochs: 20
  batch_size: 12
  learning_rate: 0.00001
  weight_decay: 0.02
  subset_fraction: 0.15
  gradient_accumulation_steps: 2
  load_balancing_coeff: 0.03

training_stage3:
  num_epochs: 15
  batch_size: 16
  learning_rate: 0.0001
  weight_decay: 0.01
  subset_fraction: 0.2
  gradient_accumulation_steps: 4
  load_balancing_coeff: 0.02

# Dataloader parameters
dataloader:
  num_workers: 5
  num_workers_s1: 14
