"""Turn a demo run's artifacts into two plots and a one-page markdown report.

The point is human inspection: after an agentic refactor you want to look at
something for thirty seconds and know whether the pipeline still behaves, rather
than read a large diff. The plots show the two things most likely to break
silently — how load is split across experts, and whether visual and text tokens
route differently.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

logger = logging.getLogger(__name__)

STAGE_METRIC_FILES = {
    "Stage 1": "loss_history_stage1.json",
    "Stage 2": "training_metrics_stage2.json",
    "Stage 2.5": "training_metrics_stage2.5.json",
    "Stage 3": "training_metrics_stage3.json",
}


def _load_json(path: Path) -> dict | None:
    try:
        return json.loads(path.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def _latest_expert_metrics(runs_dir: Path) -> dict | None:
    """Return the most recent per-epoch expert metrics dump, if Stage 3 ran."""
    files = sorted((runs_dir / "expert_metrics").glob("expert_metrics_epoch_*.json"))
    return _load_json(files[-1]) if files else None


def _plot_expert_load(metrics: dict, out_path: Path) -> None:
    """Per-layer expert load split — a flat 50/50 or a hard 100/0 both matter."""
    layers = [entry["layer"] for entry in metrics["per_layer"]]
    expert_0 = [
        entry["expert_load_distribution"].get("expert_0", 0) for entry in metrics["per_layer"]
    ]
    expert_1 = [
        entry["expert_load_distribution"].get("expert_1", 0) for entry in metrics["per_layer"]
    ]

    fig, ax = plt.subplots(figsize=(7, 3.5))
    ax.bar(layers, expert_0, label="Expert 0 (vision)", color="#4C72B0")
    ax.bar(layers, expert_1, bottom=expert_0, label="Expert 1 (text)", color="#DD8452")
    ax.axhline(50, color="grey", linestyle="--", linewidth=0.8, label="Even split")
    ax.set_xlabel("Layer")
    ax.set_ylabel("Share of routed load (%)")
    ax.set_title("Expert load distribution per layer")
    ax.set_ylim(0, 100)
    ax.set_xticks(layers)
    ax.legend(fontsize=8, loc="lower right")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def _plot_modality_routing(metrics: dict, out_path: Path) -> None:
    """Visual vs text routing — the effect the whole project is about."""
    aggregate = metrics["aggregate"]
    visual = aggregate.get("visual_routing", {})
    text = aggregate.get("text_routing", {})

    experts = ["expert_0", "expert_1"]
    positions = range(len(experts))
    width = 0.35

    fig, ax = plt.subplots(figsize=(5, 3.5))
    ax.bar(
        [p - width / 2 for p in positions],
        [visual.get(e, 0) for e in experts],
        width,
        label="Visual tokens",
        color="#4C72B0",
    )
    ax.bar(
        [p + width / 2 for p in positions],
        [text.get(e, 0) for e in experts],
        width,
        label="Text tokens",
        color="#DD8452",
    )
    ax.axhline(50, color="grey", linestyle="--", linewidth=0.8)
    ax.set_xticks(list(positions))
    ax.set_xticklabels(["Expert 0", "Expert 1"])
    ax.set_ylabel("Share of that modality's load (%)")
    ax.set_title("Routing by modality (aggregate)")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def _losses_table(runs_dir: Path) -> list[str]:
    rows = ["| Stage | Train loss | Val loss |", "|---|--:|--:|"]
    for stage, filename in STAGE_METRIC_FILES.items():
        data = _load_json(runs_dir / filename)
        if not data or not data.get("train_loss"):
            rows.append(f"| {stage} | – | – |")
            continue
        train = data["train_loss"][-1]
        val_series = data.get("val_loss") or []
        val = f"{val_series[-1]:.4f}" if val_series else "–"
        rows.append(f"| {stage} | {train:.4f} | {val} |")
    return rows


def write_report(output_root: Path, results: list[tuple[str, bool, float]]) -> Path:
    """Write figures plus demo_report.md; returns the report path."""
    runs_dir = output_root / "runs"
    figures_dir = output_root / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)

    lines = [
        "# CPU demo report",
        "",
        "Generated by `python demo/run_demo.py`. Every number here comes from the",
        "real training scripts run against tiny synthetic fixtures on CPU.",
        "",
        "## Stages",
        "",
        "| Stage | Result | Time |",
        "|---|---|--:|",
    ]
    for label, ok, elapsed in results:
        lines.append(f"| {label} | {'✅ passed' if ok else '❌ failed'} | {elapsed:.1f}s |")

    lines += ["", "## Losses", ""] + _losses_table(runs_dir)

    metrics = _latest_expert_metrics(runs_dir)
    if metrics:
        _plot_expert_load(metrics, figures_dir / "expert_load.png")
        _plot_modality_routing(metrics, figures_dir / "modality_routing.png")

        aggregate = metrics["aggregate"]
        load = aggregate.get("expert_load_distribution", {})
        visual = aggregate.get("visual_routing", {})
        text = aggregate.get("text_routing", {})
        # How differently the two modalities route. Near 0 means the router is
        # ignoring modality; the paper's Stage 3 finding is that this collapses.
        separation = abs(visual.get("expert_0", 0) - text.get("expert_0", 0))

        lines += [
            "",
            "## Routing (Stage 3, final epoch)",
            "",
            f"- Expert load: **{load.get('expert_0', 0):.1f}% / {load.get('expert_1', 0):.1f}%**",
            f"- Mean routing entropy: **{aggregate.get('avg_routing_entropy', 0):.4f}** "
            "(ln 2 ≈ 0.693 is maximum uncertainty for two experts)",
            f"- High-confidence tokens: **{aggregate.get('high_confidence_fraction', 0):.1%}**",
            f"- Modality separation: **{separation:.1f} points** "
            "(difference in how visual vs text tokens use Expert 0)",
            "",
            "![Expert load](figures/expert_load.png)",
            "",
            "![Routing by modality](figures/modality_routing.png)",
            "",
            "> On an untrained tiny model these sit near an even split — that is the",
            "> expected result, not a bug. What matters for review is that the metrics",
            "> are produced at all and move when the routing code changes.",
        ]
    else:
        lines += [
            "",
            "## Routing",
            "",
            "_Stage 3 did not run, so no routing metrics were produced._",
        ]

    report_path = output_root / "demo_report.md"
    report_path.write_text("\n".join(lines) + "\n")
    logger.info("Report written to %s", report_path)
    return report_path
